server:
  port: 2300
cas:
  client:
    client-id: client
    client-secret: client_secret
    token-path: http://localhost:2200/token
    token-info-path: http://localhost:2200/token_info
    refresh-token-path: http://localhost:2200/refresh_token