spring:
  redis:
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cas
    username: root
    password: 123456
mall:
  auth:
    swagger-enable: true
server:
  port: 2200